= Vert.x Service Proxy
:toc: left

当你编写Vert.x程序的时候，你也许想将某处独立服务功能提供给其他程序使用。这时候可以使用服务代理了。 它可以让你在事件总线上公开你的 _服务_ , 因此，任何Vert.x程序只要知道其推送的 _地址_ 就可以消费使用它。

 _服务_ 它是遵循Java接口定义，方法定义必须遵循 _异步规范_. 更深层次下,
在事件总线上发送请求消息并调用服务响应请求。 但是为了更简单使用,
他会成为一个 _代理_ 可以直接调用 (使用服务接口的API).

[[_using_vert_x_service_proxies]]
== 使用Vert.x服务代理

使用Vert.x Service Proxy之前，你必须在你得项目当中添加 _依赖_ :

* Maven (在 `pom.xml` 文件中):

[source,xml,subs="+attributes"]
----
<dependency>
 <groupId>io.vertx</groupId>
 <artifactId>vertx-service-proxy</artifactId>
 <version>4.0.0</version>
</dependency>
----

* Gradle (在 `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-service-proxy:4.0.0'
----

为了 *实现* 服务代理, 您还需要添加:

* Maven (在 `pom.xml` 文件中):

[source,xml,subs="+attributes"]
----
<dependency>
 <groupId>io.vertx</groupId>
 <artifactId>vertx-codegen</artifactId>
 <version>4.0.0</version>
 <scope>provided</scope>
</dependency>
----

* Gradle版本小于 5 的情况(在 `build.gradle` 文件中):

[source,groovy,subs="+attributes"]
----
compileOnly 'io.vertx:vertx-codegen:4.0.0'
----

* Gradle版本大于等于 5 (在 `build.gradle` 文件中):

[source,groovy,subs="+attributes"]
----
annotationProcessor 'io.vertx:vertx-codegen:4.0.0:processor'
annotationProcessor 'io.vertx:vertx-service-proxy:4.0.0'
----

注意：因为服务代理类是通过代码生成的缘故，每当你你修改了 _服务接口_ 你必须重新编译编码，以重新 生成代理类。

如果你要生成不同语言的代理类，你需要添加相应的依赖。例如，生成Groovy需要添加 `vertx-lang-groovy` 依赖

[[_introduction_to_service_proxies]]
== 服务代理简介

让我看看服务代理它怎么用。 如果你在事件总线上公开 _数据库服务_ 你可以执行下面的操作

[source,java]
----
JsonObject message = new JsonObject();

message
  .put("collection", "mycollection")
  .put("document", new JsonObject().put("name", "tim"));

DeliveryOptions options = new DeliveryOptions().addHeader("action", "save");

vertx.eventBus()
  .request("database-service-address", message, options)
  .onSuccess(msg -> {
    // 完成
  }).onFailure(err -> {
  // 失败
});
----

When creating a service there's a certain amount of boilerplate code to listen on the event bus for incoming messages, route them to the appropriate method and return results on the event bus.

使用Vert.x服务代理时, you can avoid writing all that boilerplate code and concentrate on 编写服务

在你编写的Java接口上面打上 `@ProxyGen` 注解, 例如:

[source,java]
----
@ProxyGen
public interface SomeDatabaseService {

 // 几个工程方法用于创建实例
 static SomeDatabaseService create(Vertx vertx) {
   return new SomeDatabaseServiceImpl(vertx);
 }

 static SomeDatabaseService createProxy(Vertx vertx,
   String address) {
   return new SomeDatabaseServiceVertxEBProxy(vertx, address);
 }

// 服务实际的接口订单
void save(String collection, JsonObject document,
  Handler<AsyncResult<Void>> resultHandler);
}
----

你还需要编写 `package-info.java` 文件，位置处于接口定义包中.
这个包还需要 `@ModuleGen` 注解，以方便Vert.x代码生成器生成事件总线代理代码。

.package-info.java
[source,java]
----
@io.vertx.codegen.annotations.ModuleGen(groupPackage = "io.vertx.example", name = "services")
package io.vertx.example;
----

Given the interface, Vert.x will generate all the boilerplate code required to access your service over the event bus, and it will also generate a *client side proxy* for your service, so your clients can use a rich idiomatic API for your service instead of having to manually craft event bus messages to send.
The client side proxy will work irrespective of where your service actually lives on the event bus (potentially on a different machine).

That means you can interact with your service like this:

[source,java]
----
SomeDatabaseService service = SomeDatabaseService
  .createProxy(vertx, "database-service-address");

// Save some data in the database - this time using the proxy
service.save(
  "mycollection",
  new JsonObject().put("name", "tim"),
  res2 -> {
    if (res2.succeeded()) {
      // done
    }
  });
----

You can also combine `@ProxyGen` with language API code generation (`@VertxGen`) in order to create service stubs in any of the languages supported by Vert.x - this means you can write your service once in Java and interact with it through an idiomatic other language API irrespective of whether the service lives locally or is somewhere else on the event bus entirely.
For this don't forget to add the dependency on your language in your build descriptor:

[source,java]
----
@ProxyGen // Generate service proxies
@VertxGen // Generate the clients
public interface SomeDatabaseService {
 // ...
}
----

[[_async_interface]]
== 异步接口

To be used by the service-proxy generation, the _service interface_ must comply to a couple of rules.
First it should follow the async pattern.
To return a result, the method should declare a `Handler<AsyncResult<ResultType>>` parameter.
`ResultType` can be another proxy (and so a proxies can be factories for other proxies).

Let's see an example:

[source,java]
----
@ProxyGen
public interface SomeDatabaseService {

// A couple of factory methods to create an instance and a proxy

static SomeDatabaseService create(Vertx vertx) {
  return new SomeDatabaseServiceImpl(vertx);
}

static SomeDatabaseService createProxy(Vertx vertx, String address) {
  return new SomeDatabaseServiceVertxEBProxy(vertx, address);
}

// A method notifying the completion without a result (void)
void save(String collection, JsonObject document,
  Handler<AsyncResult<Void>> result);

// A method providing a result (a json object)
void findOne(String collection, JsonObject query,
  Handler<AsyncResult<JsonObject>> result);

// Create a connection
void createConnection(String shoeSize,
  Handler<AsyncResult<MyDatabaseConnection>> resultHandler);

}
----

with:

[source,java]
----
@ProxyGen
@VertxGen
public interface MyDatabaseConnection {

void insert(JsonObject someData);

void commit(Handler<AsyncResult<Void>> resultHandler);

@ProxyClose
void close();
}
----

You can also declare that a particular method unregisters the proxy by annotating it with the `@ProxyClose`
annotation.
The proxy instance is disposed when this method is called.

More constraints on the _service interfaces_ are described below.

[[_security]]
== 安全

Service proxies can perform basic security using a simple interceptor.
A authentication provider must be provided, optionally `Authorization`s can be added and in this case an `AuthorizationProvider` must also be present.
Note that the authentication works based on tokens, that are extracted from the `auth-token` header.

[source,java]
----
SomeDatabaseService service = new SomeDatabaseServiceImpl();
// Register the handler
new ServiceBinder(vertx)
  .setAddress("database-service-address")
  // Secure the messages in transit
  .addInterceptor(
    new ServiceAuthInterceptor()
      // Tokens will be validated using JWT authentication
      .setAuthenticationProvider(JWTAuth.create(vertx, new JWTAuthOptions()))
      // optionally we can secure permissions too:

      // an admin
      .addAuthorization(RoleBasedAuthorization.create("admin"))
      // that can print
      .addAuthorization(PermissionBasedAuthorization.create("print"))

      // where the authorizations are loaded, let's assume from the token
      // but they could be loaded from a database or a file if needed
      .setAuthorizationProvider(
        JWTAuthorization.create("permissions")))

  .register(SomeDatabaseService.class, service);
----

[[_code_generation]]
== 代码生成

Service annotated with `@ProxyGen` annotation trigger the generation of the service helper classes:

- The service proxy: a compile time generated proxy that uses the `EventBus` to interact with the service via messages
- The service handler: a compile time generated `EventBus` handler that reacts to events sent by the proxy

Generated proxies and handlers are named after the service class, for example if the service is named `MyService`
the handler is called `MyServiceProxyHandler` and the proxy is called `MyServiceEBProxy`.

In addition Vert.x Core provides a generator creating data object converters to ease data object usage in service proxies.
Such converter provides a basis for the `JsonObject` constructor and the `toJson()` method that are necessary for using data objects in service proxies.

The _codegen_ annotation processor generates these classes at compilation time.
It is a feature of the Java compiler so _no extra step_ is required, it is just a matter of configuring correctly your build:

Just add the `io.vertx:vertx-codegen:processor` and `io.vertx:vertx-service-proxy`
dependencies to your build.

Here a configuration example for Maven:

[source,xml]
----
<dependency>
 <groupId>io.vertx</groupId>
 <artifactId>vertx-codegen</artifactId>
 <version>4.0.0</version>
 <classifier>processor</classifier>
</dependency>
<dependency>
 <groupId>io.vertx</groupId>
 <artifactId>vertx-service-proxy</artifactId>
 <version>4.0.0</version>
</dependency>
----

This feature can also be used in Gradle:

[source]
----
compile "io.vertx:vertx-codegen:4.0.0:processor"
compile "io.vertx:vertx-service-proxy:4.0.0"
----

IDE provides usually support for annotation processors.

The codegen `processor` classifier adds to the jar the automatic configuration of the service proxy annotation processor via the `META-INF/services` plugin mechanism.

If you want you can use it too with the regular jar but you need then to declare the annotation processor explicitly, for instance in Maven:

[source,xml]
----
<plugin>
 <artifactId>maven-compiler-plugin</artifactId>
 <configuration>
   <annotationProcessors>
     <annotationProcessor>io.vertx.codegen.CodeGenProcessor</annotationProcessor>
   </annotationProcessors>
 </configuration>
</plugin>
----

[[_exposing_your_service]]
== 公开服务

Once you have your _service interface_, compile the source to generate the stub and proxies.
Then, you need some code to "register" your service on the event bus:

[source,java]
----
SomeDatabaseService service = new SomeDatabaseServiceImpl();
// Register the handler
new ServiceBinder(vertx)
  .setAddress("database-service-address")
  .register(SomeDatabaseService.class, service);
----

This can be done in a verticle, or anywhere in your code.

Once registered, the service becomes accessible.
If you are running your application on a cluster, the service is available from any host.

To withdraw your service, use the `link:../../apidocs/io/vertx/serviceproxy/ServiceBinder.html#unregister-io.vertx.core.eventbus.MessageConsumer-[unregister]`
method:

[source,java]
----
ServiceBinder binder = new ServiceBinder(vertx);

// Create an instance of your service implementation
SomeDatabaseService service = new SomeDatabaseServiceImpl();
// Register the handler
MessageConsumer<JsonObject> consumer = binder
  .setAddress("database-service-address")
  .register(SomeDatabaseService.class, service);

// ....

// Unregister your service.
binder.unregister(consumer);
----

[[_proxy_creation]]
== 代理创建

Now that the service is exposed, you probably want to consume it.
For this, you need to create a proxy.
The proxy can be created using the `link:../../apidocs/io/vertx/serviceproxy/ServiceProxyBuilder.html[ServiceProxyBuilder]` class:

[source,java]
----
ServiceProxyBuilder builder = new ServiceProxyBuilder(vertx)
  .setAddress("database-service-address");

SomeDatabaseService service = builder.build(SomeDatabaseService.class);
// or with delivery options:
SomeDatabaseService service2 = builder.setOptions(options)
  .build(SomeDatabaseService.class);
----

The second method takes an instance of `link:../../apidocs/io/vertx/core/eventbus/DeliveryOptions.html[DeliveryOptions]` where you can configure the message delivery (such as the timeout).

Alternatively, you can use the generated proxy class.
The proxy class name is the _service interface_ class name followed by `VertxEBProxy`.
For instance, if your _service interface_ is named `SomeDatabaseService`, the proxy class is named `SomeDatabaseServiceVertxEBProxy`.

Generally, _service interface_ contains a `createProxy` static method to create the proxy.
But this is not required:

[source,java]
----
@ProxyGen
public interface SomeDatabaseService {

// Method to create the proxy.
static SomeDatabaseService createProxy(Vertx vertx, String address) {
  return new SomeDatabaseServiceVertxEBProxy(vertx, address);
}

// ...
}
----

[[_error_handling]]
== 错误处理

Service methods may return errors to the client by passing a failed `Future` containing a `link:../../apidocs/io/vertx/serviceproxy/ServiceException.html[ServiceException]`
instance to the method's `Handler`.
A `ServiceException` contains an `int` failure code, a message, and an optional
`JsonObject` containing any extra information deemed important to return to the caller.
For convenience, the
`link:../../apidocs/io/vertx/serviceproxy/ServiceException.html#fail-int-java.lang.String-[ServiceException.fail]` factory method can be used to create an instance of
`ServiceException` already wrapped in a failed `Future`.
For example:

[source,java]
----
public class SomeDatabaseServiceImpl implements SomeDatabaseService {
private static final BAD_SHOE_SIZE = 42;
private static final CONNECTION_FAILED = 43;

 // Create a connection
 void createConnection(String shoeSize, Handler<AsyncResult<MyDatabaseConnection>> resultHandler) {
   if (!shoeSize.equals("9")) {
     resultHandler.handle(ServiceException.fail(BAD_SHOE_SIZE, "The shoe size must be 9!",
       new JsonObject().put("shoeSize", shoeSize));
    } else {
       doDbConnection(result -> {
         if (result.succeeded()) {
           resultHandler.handle(Future.succeededFuture(result.result()));
         } else {
           resultHandler.handle(ServiceException.fail(CONNECTION_FAILED, result.cause().getMessage()));
         }
       });
    }
 }
}
----

The client side can then check if the `Throwable` it receives from a failed `AsyncResult` is a `ServiceException`, and if so, check the specific error code inside.
It can use this information to differentiate business logic errors from system errors (like the service not being registered with the Event Bus), and to determine exactly which business logic error occurred.

[source,java]
----
public void foo(String shoeSize, Handler<AsyncResult<JsonObject>> handler) {
 SomeDatabaseService service = SomeDatabaseService.createProxy(vertx, SERVICE_ADDRESS);
 service.createConnection("8", result -> {
   if (result.succeeded()) {
     // Do success stuff.
   } else {
     if (result.cause() instanceof ServiceException) {
       ServiceException exc = (ServiceException) result.cause();
       if (exc.failureCode() == SomeDatabaseServiceImpl.BAD_SHOE_SIZE) {
         handler.handle(Future.failedFuture(
           new InvalidInputError("You provided a bad shoe size: " +
             exc.getDebugInfo().getString("shoeSize"))
         ));
       } else if (exc.failureCode() == SomeDatabaseServiceImpl.CONNECTION) {
         handler.handle(Future.failedFuture(
           new ConnectionError("Failed to connect to the DB")));
       }
     } else {
       // Must be a system error (e.g. No service registered for the proxy)
       handler.handle(Future.failedFuture(
         new SystemError("An unexpected error occurred: + " result.cause().getMessage())
       ));
     }
   }
 }
}
----

If desired, service implementations may also return a sub-class of `ServiceException`, as long as a default `MessageCodec` is registered for it . For example, given the following `ServiceException` sub-class:

[source,java]
----
class ShoeSizeException extends ServiceException {
 public static final BAD_SHOE_SIZE_ERROR = 42;

 private final String shoeSize;

 public ShoeSizeException(String shoeSize) {
   super(BAD_SHOE_SIZE_ERROR, "In invalid shoe size was received: " + shoeSize);
   this.shoeSize = shoeSize;
 }

 public String getShoeSize() {
   return extra;
 }

 public static <T> AsyncResult<T> fail(int failureCode, String message, String shoeSize) {
   return Future.failedFuture(new MyServiceException(failureCode, message, shoeSize));
 }
}
----

As long as a default `MessageCodec` is registered, the Service implementation can return the custom exception directly to the caller:

[source,java]
----
public class SomeDatabaseServiceImpl implements SomeDatabaseService {
 public SomeDataBaseServiceImpl(Vertx vertx) {
   // Register on the service side. If using a local event bus, this is all
   // that's required, since the proxy side will share the same Vertx instance.
 SomeDatabaseService service = SomeDatabaseService.createProxy(vertx, SERVICE_ADDRESS);
   vertx.eventBus().registerDefaultCodec(ShoeSizeException.class,
     new ShoeSizeExceptionMessageCodec());
 }

 // Create a connection
 void createConnection(String shoeSize, Handler<AsyncResult<MyDatabaseConnection>> resultHandler) {
   if (!shoeSize.equals("9")) {
     resultHandler.handle(ShoeSizeException.fail(shoeSize));
   } else {
     // Create the connection here
     resultHandler.Handle(Future.succeededFuture(myDbConnection));
   }
 }
}
----

Finally, the client can now check for the custom exception:

[source,java]
----
public void foo(String shoeSize, Handler<AsyncResult<JsonObject>> handler) {
 // If this code is running on a different node in the cluster, the
 // ShoeSizeExceptionMessageCodec will need to be registered with the
 // Vertx instance on this node, too.
 SomeDatabaseService service = SomeDatabaseService.createProxy(vertx, SERVICE_ADDRESS);
 service.createConnection("8", result -> {
   if (result.succeeded()) {
     // Do success stuff.
   } else {
     if (result.cause() instanceof ShoeSizeException) {
       ShoeSizeException exc = (ShoeSizeException) result.cause();
       handler.handle(Future.failedFuture(
         new InvalidInputError("You provided a bad shoe size: " + exc.getShoeSize())));
     } else {
       // Must be a system error (e.g. No service registered for the proxy)
       handler.handle(Future.failedFuture(
         new SystemError("An unexpected error occurred: + " result.cause().getMessage())
       ));
     }
   }
 }
}
----

Note that if you're clustering `Vertx` instances, you'll need to register the custom Exception's `MessageCodec`
with each `Vertx` instance in the cluster.

[[_restrictions_for_service_interface]]
== 接口类型限制

There are restrictions on the types and return values that can be used in a service method so that these are easy to marshall over event bus messages and so they can be used asynchronously.
They are:

=== 返回类型

必须是以下两种:

* `void`
* `@Fluent` 返回服务实例本身(即:`this`):

[source,java]
----
@Fluent
SomeDatabaseService doSomething();
----

This is because methods must not block and it's not possible to return a result immediately without blocking if the service is remote.

=== 参数类型

类型简写说明：

- `JSON` = `JsonObject 或 JsonArray`
- `PRIMITIVE` = 任何原始类型或被自动拆装箱的原始类型

参数可以是以下任意一种:

* `JSON`
* `PRIMITIVE`
* `List<JSON>`
* `List<PRIMITIVE>`
* `Set<JSON>`
* `Set<PRIMITIVE>`
* `Map<String, JSON>`
* `Map<String, PRIMITIVE>`
* 任何 _枚举_ 类型
* 任何被打上 `@DataObject` 注解的实体类

If an asynchronous result is required a last parameter of type `Handler<AsyncResult<R>>` can be provided.

`R` can be any of:

* `JSON`
* `PRIMITIVE`
* `List<JSON>`
* `List<PRIMITIVE>`
* `Set<JSON>`
* `Set<PRIMITIVE>`
* Any _Enum_ type
* Any class annotated with `@DataObject`
* Another proxy

=== 重载方法

There must be no overloaded service methods. (_i.e._ more than one with the same name, regardless the signature).

[_convention_for_invoking_services_over_the_event_bus_without_proxies]
== 通过事件总线调用服务的规则 (不使用服务代理)

Service Proxies assume that event bus messages follow a certain format so they can be used to invoke services.

Of course, you don't *have to* use client proxies to access remote service if you don't want to.
It's perfectly acceptable to interact with them by just sending messages over the event bus.

In order for services to be interacted with a consistent way the following message formats *must be used* for any Vert.x services.

The format is very simple:

* There should be a header called `action` which gives the name of the action to perform.
* The body of the message should be a `JsonObject`, there should be one field in the object for each argument needed by the action.

For example to invoke an action called `save` which expects a String collection and a JsonObject document:

----
Headers:
   "action": "save"
Body:
   {
       "collection", "mycollection",
       "document", {
           "name": "tim"
       }
   }
----

The above convention should be used whether or not service proxies are used to create services, as it allows services to be interacted with consistently.

In the case where service proxies are used the "action" value should map to the name of an action method in the service interface and each `[key, value]` in the body should map to a `[arg_name, arg_value]` in the action method.

For return values the service should use the `message.reply(...)` method to send back a return value - this can be of any type supported by the event bus.
To signal a failure the method `message.fail(...)` should be used.

If you are using service proxies the generated code will handle this for you automatically.