name: Deploy to gitee.com

on:
  push:
    branches: [ master, preview ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Get basePath from branch
        id: basePath
        run: |
          REF=${REF#"refs/heads/"}
          if [ $REF == 'master' ]
          then
              echo "::set-output name=basePath::"
          elif [ $REF == 'preview' ]
          then
              echo "::set-output name=basePath::_preview"
          else
              echo "::set-output name=basePath::_preview/$REF"
          fi
        env:
          REF: ${{ github.ref }}

      - run: npm ci
      - run: npm run update-docs
      - run: npm run build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERTX_WEBSITE_BASEPATH: ${{ steps.basePath.outputs.basePath }}
          BUILD_SITE: vertx-china.gitee.io

      - uses: okou19900722/workflows/git-deploy@v1
        with:
          ssh-key: ${{ secrets.GITEE_TOKEN }}
          src-dir: out
          branch: master
          repo-url: git@gitee.com:vertx-china/vertx-china.git
          user-name: okou19900722
          user-email: 512058895@qq.com
          commit-message: publish
