name: Node.js CI

on:
  push:
    branches: [ master, preview ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Get basePath from branch
        id: basePath
        run: |
          REF=${REF#"refs/heads/"}
          if [ $REF == 'master' ]
          then
              echo "::set-output name=basePath::"
          elif [ $REF == 'preview' ]
          then
              echo "::set-output name=basePath::_preview"
          else
              echo "::set-output name=basePath::_preview/$REF"
          fi
        env:
          REF: ${{ github.ref }}

      - run: npm ci
      - run: npm run update-docs
      - run: npm run build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTRIBUTE_FETCH_TOKEN: ${{ secrets.CONTRIBUTE_FETCH_TOKEN }}
          VERTX_WEBSITE_BASEPATH: ${{ steps.basePath.outputs.basePath }}

      - name: Clone current GitHub Pages repo
        run: git clone --depth 1 https://github.com/vertx-china/vertx-china.github.io.git

      - name: Clean output directory
        run: |
          rm -rf vertx-china.github.io/.git
          rm vertx-china.github.io/.nojekyll

      - name: Clean preview directory
        run: rm -rf vertx-china.github.io/${{ steps.basePath.outputs.basePath }}
        if: ${{ github.ref != 'refs/heads/master' }}

      - name: Copy build to preview directory
        run: |
          mkdir -p vertx-china.github.io/${{ steps.basePath.outputs.basePath }}
          mv out/* vertx-china.github.io/${{ steps.basePath.outputs.basePath }}
        if: ${{ github.ref != 'refs/heads/master' }}

      - name: Clean output directory (except preview directory)
        run: |
          mkdir -p vertx-china.github.io.tmp
          mv vertx-china.github.io/_preview vertx-china.github.io.tmp/_preview || true
          rm -rf vertx-china.github.io
          mv vertx-china.github.io.tmp vertx-china.github.io
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Copy build to output directory
        run: mv out/* vertx-china.github.io
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: vertx-china/vertx-china.github.io
          publish_branch: master
          publish_dir: vertx-china.github.io
#          cname: vertx.io

      - name: Deploy to Gitee Pages
        uses: okou19900722/workflows/git-deploy@v1
        with:
          ssh-key: ${{ secrets.GITEE_TOKEN }}
          src-dir: vertx-china.github.io
          branch: master
          repo-url: git@gitee.com:vertx-china/vertx-china.git
          user-name: okou19900722
          user-email: 512058895@qq.com
          commit-message: publish
          force-orphan: true

      - uses: okou19900722/workflows/git-deploy@v1
        with:
          ssh-key: ${{ secrets.CODING_TOKEN }}
          src-dir: vertx-china.github.io
          branch: master
          repo-url: git@e.coding.net:lippen/cn.vertx.tk.git
          user-name: okou19900722
          user-email: 512058895@qq.com
          commit-message: publish
          force-orphan: true

      - name: Refresh Gitee Pages
        uses: okou19900722/gitee-pages@v1
        with:
          username: "okou19900722"
          password: ${{ secrets.GITEE_PASSWORD }}
          repository: "https://gitee.com/vertx-china/vertx-china"
          branch: "master"
          directory: ""
          https: 'true'
        env:
          RUNNER_DEBUG: 1
