name: Node.js CI

on:
  push:
    branches: [ master, preview ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"

#      - uses: actions/cache@v2
#        with:
#          path: .cache
#          key: ${{ runner.os }}-build-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-build-

      - name: Get basePath from branch
        id: basePath
        run: |
          REF=${REF#"refs/heads/"}
          if [ $REF == 'master' ]
          then
              echo "::set-output name=basePath::"
          elif [ $REF == 'preview' ]
          then
              echo "::set-output name=basePath::_preview"
          else
              echo "::set-output name=basePath::_preview/$REF"
          fi
        env:
          REF: ${{ github.ref }}

      - run: npm ci
      - run: npm run update-docs
      - run: npm run build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERTX_WEBSITE_BASEPATH: ${{ steps.basePath.outputs.basePath }}

      - name: Clone current GitHub Pages repo
        run: git clone --depth 1 https://github.com/vertx-web-site/vertx-web-site.github.io.git

      - name: Clean output directory
        run: |
          rm -rf vertx-web-site.github.io/.git
          rm vertx-web-site.github.io/.nojekyll

      - name: Clean preview directory
        run: rm -rf vertx-web-site.github.io/${{ steps.basePath.outputs.basePath }}
        if: ${{ github.ref != 'refs/heads/master' }}

      - name: Copy build to preview directory
        run: |
          mkdir -p vertx-web-site.github.io/${{ steps.basePath.outputs.basePath }}
          mv out/* vertx-web-site.github.io/${{ steps.basePath.outputs.basePath }}
        if: ${{ github.ref != 'refs/heads/master' }}

      - name: Clean output directory (except preview directory)
        run: |
          mkdir -p vertx-web-site.github.io.tmp
          mv vertx-web-site.github.io/_preview vertx-web-site.github.io.tmp/_preview || true
          rm -rf vertx-web-site.github.io
          mv vertx-web-site.github.io.tmp vertx-web-site.github.io
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Copy build to output directory
        run: mv out/* vertx-web-site.github.io
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: vertx-web-site/vertx-web-site.github.io
          publish_branch: master
          publish_dir: vertx-web-site.github.io
          cname: vertx.io
