name: Sync to Coding.net

on:
  push:
    branches: [ master, preview ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: okou19900722/workflows/git-sync@v1
        name: Sync repo to gitee
        with:
          ssh-key: ${{ secrets.GITEE_TOKEN }}
          repo-url: git@gitee.com:vertx-china/vertx-web-site.git

